### ISSUE TITLE
another new card statement file?

### ISSUE THREAD

**Issue by kintaro1981** [frankIT/ofxstatement-fineco#9]
It seems that the card statement changed again:

New:
`
['Data operazione', 'Data registrazione', 'Descrizione', 'Stato', 'Tipologia', 'Rimborso', 'Importo in EUR']`

Pull Request: https://github.com/frankIT/ofxstatement-fineco/pull/11

**Comment by frankIT** [comment]
I cannot reproduce.. when i export the xls file from [https://finecobank.com/conto-e-carte/carte-e-bancomat/movimenti](https://finecobank.com/conto-e-carte/carte-e-bancomat/movimenti) i still get the old heading:
`['Data operazione', 'Data registrazione', 'Descrizione', 'Tipo spesa', 'Tipo rimborso', 'Importo in EUR']`
Can you confirm that you export the file from the same link?
If so, it may be due to different kind of transactions in the statement...just guessing what could be the trigger to output different headings in the file.
Until the old header file is available it has to be supported, but new variations needs to be handled as well. So i'll wait to understand this a bit more before accepting the mentioned pull request as is

**Comment by kintaro1981** [comment]
https://finecobank.com/conto-e-carte/carte-e-bancomat/movimenti takes me to an error page.

I download the cards' xls from:
https://finecobank.com/conto-e-carte/carte-e-bancomat/excel

Maybe it's because I have Money Map disabled?
Or because I have two cards? A credit card (also bancomat) and a bancomat?

**Comment by frankIT** [comment]
Updated cards support as the current file template:
`["Intestatario carta", "Numero carta", "Data operazione", "Data registrazione", "Descrizione", "Stato operazione", "Tipo operazione", "Circuito", "Tipo rimborso",	"Importo"]`

82bb36430f25ad5afb359b22c2e192e51eb4569d
